name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Building
      run: cd go-h2c; go build -v ./...
    - name: Testing
      run: cd go-h2c; go test -v ./... -cover --count=1
